-- MySQL Script generated by MySQL Workbench
-- Thu Mar  2 15:29:06 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';

-- -----------------------------------------------------
-- Schema alumni_email
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `alumni_email` ;

-- -----------------------------------------------------
-- Schema alumni_email
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alumni_email` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `alumni_email` ;

-- -----------------------------------------------------
-- Table `log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `log` (
  `log_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `request_no` VARCHAR(10) NOT NULL,
  `module` VARCHAR(45) NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  `details` TEXT NOT NULL,
  `session_id` VARCHAR(128) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `user_agent` VARCHAR(120) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `idx_log_request_no` ON `log` (`request_no` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `alumni_email_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alumni_email_session` (
  `id` VARCHAR(128) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `timestamp` INT UNSIGNED NOT NULL DEFAULT 0,
  `data` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `idx_alum_email_session_time` ON `alumni_email_session` (`timestamp` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `captcha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captcha` (
  `captcha_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `captcha_time` INT UNSIGNED NOT NULL,
  `session_id` VARCHAR(128) NOT NULL,
  `word` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`captcha_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `idx_captcha_word` ON `captcha` (`word` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin` (
  `admin_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `role` VARCHAR(10) NOT NULL,
  `first_login` DATETIME NOT NULL,
  `last_login` DATETIME NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `username_UNIQUE` ON `admin` (`username` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `request` (
  `request_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_no` CHAR(10) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `date_requested` DATETIME NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  `waiver_1` TINYINT(1) NOT NULL,
  `waiver_2` TINYINT(1) NOT NULL,
  `waiver_3` TINYINT(1) NOT NULL,
  `confirmation_code` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`request_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `request_no_UNIQUE` ON `request` (`request_no` ASC);

SHOW WARNINGS;
CREATE INDEX `idx_request_status` ON `request` (`status` ASC, `date_requested` ASC);

SHOW WARNINGS;
CREATE INDEX `idx_request_code` ON `request` (`confirmation_code` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal` (
  `request_id` INT UNSIGNED NOT NULL,
  `title_simple` VARCHAR(5) NOT NULL,
  `title_preferred` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `middle_name` VARCHAR(50) NOT NULL,
  `maiden_name` VARCHAR(50) NOT NULL,
  `nickname` VARCHAR(20) NOT NULL,
  `sex` CHAR(1) NOT NULL,
  `birthdate` DATE NOT NULL,
  `birth_place` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`request_id`),
  CONSTRAINT `fk_profile_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `request` (`request_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus` (
  `campus_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campus_name` VARCHAR(45) NOT NULL,
  `campus_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`campus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `campus_name_UNIQUE` ON `campus` (`campus_name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `academic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academic` (
  `request_id` INT UNSIGNED NOT NULL,
  `student_no` VARCHAR(9) NOT NULL,
  `campus_id` TINYINT UNSIGNED NOT NULL,
  `college` VARCHAR(100) NOT NULL,
  `course` VARCHAR(100) NOT NULL,
  `year_started` YEAR NOT NULL,
  `year_graduated` YEAR NOT NULL,
  `honor` VARCHAR(50) NOT NULL,
  `other_degrees` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`request_id`),
  CONSTRAINT `fk_academic_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `request` (`request_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_academic_campus1`
    FOREIGN KEY (`campus_id`)
    REFERENCES `campus` (`campus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_academic_campus1_idx` ON `academic` (`campus_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contact` (
  `request_id` INT UNSIGNED NOT NULL,
  `address_1` VARCHAR(100) NOT NULL,
  `address_2` VARCHAR(100) NOT NULL,
  `address_3` VARCHAR(50) NOT NULL,
  `address_4` VARCHAR(50) NOT NULL,
  `address_zip` VARCHAR(15) NOT NULL,
  `tel_no` VARCHAR(50) NOT NULL,
  `mobile_no` VARCHAR(50) NOT NULL,
  `website` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`request_id`),
  CONSTRAINT `fk_contact_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `request` (`request_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work` (
  `request_id` INT UNSIGNED NOT NULL,
  `company_name` VARCHAR(100) NOT NULL,
  `occupation` VARCHAR(100) NOT NULL,
  `work_address_1` VARCHAR(100) NOT NULL,
  `work_address_2` VARCHAR(100) NOT NULL,
  `work_address_3` VARCHAR(50) NOT NULL,
  `work_address_4` VARCHAR(50) NOT NULL,
  `work_address_zip` VARCHAR(15) NOT NULL,
  `work_tel_no` VARCHAR(50) NOT NULL,
  `work_mobile_no` VARCHAR(50) NOT NULL,
  `fax_no` VARCHAR(50) NOT NULL,
  `work_website` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`request_id`),
  CONSTRAINT `fk_employment_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `request` (`request_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `membership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `membership` (
  `membership_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_id` INT UNSIGNED NOT NULL,
  `category` TINYINT UNSIGNED NOT NULL,
  `organization` VARCHAR(100) NOT NULL,
  `period` VARCHAR(50) NOT NULL,
  `position` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`membership_id`),
  CONSTRAINT `fk_membership_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `request` (`request_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exam` (
  `request_id` INT UNSIGNED NOT NULL,
  `exam_name` VARCHAR(100) NOT NULL,
  `exam_place` VARCHAR(50) NOT NULL,
  `exam_date` VARCHAR(50) NOT NULL,
  `rating` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`request_id`),
  CONSTRAINT `fk_exam_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `request` (`request_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `award`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `award` (
  `award_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_id` INT UNSIGNED NOT NULL,
  `award_name` VARCHAR(100) NOT NULL,
  `award_date` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`award_id`),
  CONSTRAINT `fk_award_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `request` (`request_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_award_request1_idx` ON `award` (`request_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `family` (
  `family_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `relation` VARCHAR(50) NOT NULL,
  `campus_id` TINYINT UNSIGNED NOT NULL,
  `college` VARCHAR(100) NOT NULL,
  `course` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `year_graduated` YEAR NOT NULL,
  PRIMARY KEY (`family_id`),
  CONSTRAINT `fk_family_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `request` (`request_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_family_campus1`
    FOREIGN KEY (`campus_id`)
    REFERENCES `campus` (`campus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_family_campus1_idx` ON `family` (`campus_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `college`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `college` (
  `college_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `college_name` VARCHAR(100) NOT NULL,
  `college_code` VARCHAR(45) NOT NULL,
  `campus_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`college_id`),
  CONSTRAINT `fk_college_campus1`
    FOREIGN KEY (`campus_id`)
    REFERENCES `campus` (`campus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_college_campus1_idx` ON `college` (`campus_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course` (
  `course_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(100) NOT NULL,
  `degree` VARCHAR(45) NOT NULL,
  `major` VARCHAR(45) NOT NULL,
  `college_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`course_id`),
  CONSTRAINT `fk_course_college1`
    FOREIGN KEY (`college_id`)
    REFERENCES `college` (`college_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_course_college1_idx` ON `course` (`college_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
